### ISSUE TITLE
Problem with connecting to SQLite  trying to run "npm start"

### ISSUE THREAD

**Issue by owendall** [mike-north/vscode-fundamentals#9]
I can connect fine with sqlite3 from the command line.but get this:

```
/Users/owendall/Desktop/github-applications/fem/vscode-fundamentals/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31
        throw new Error('Please install sqlite3 package manually');
        ^

Error: Please install sqlite3 package manually
    at new ConnectionManager (/Users/owendall/Desktop/github-applications/fem/vscode-fundamentals/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31:15)
    at new SqliteDialect (/Users/owendall/Desktop/github-applications/fem/vscode-fundamentals/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/Users/owendall/Desktop/github-applications/fem/vscode-fundamentals/node_modules/sequelize/lib/sequelize.js:228:20)
    at fs.exists (/Users/owendall/Desktop/github-applications/fem/vscode-fundamentals/server/db.js:21:23)
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
```
I updated SQLite3, but no difference...

Suggestions?

**Comment by owendall** [comment]
Never mind, got it running after pulling again after Sqlite3
